import React from "react";
import type { Metadata } from "next";
import "./globals.scss";
import { Providers } from "@/components/provider/Provider";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.min.css";

export const metadata: Metadata = {
  title: "AgencyTool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          {children}
          <ToastContainer limit={4} />
        </body>
      </Providers>
    </html>
  );
}
